import { Images } from '../style/images';

export const browseDummyDataData = [
    {
        id: 1,
        description: 'A very nice looking item with more description',
        price: 80.0,
        salePrice: 50.0,
        image: Images.PH1,
        isSellingFast: true,
    },
    {
        id: 2,
        description: 'A very nice looking item',
        price: 50.0,
        salePrice: null,
        image: Images.PH2,
        isSellingFast: true,
    },
    {
        id: 3,
        description: 'A very nice looking item',
        price: 23.0,
        salePrice: null,
        image: Images.PH3,
        isSellingFast: false,
    },
    {
        id: 4,
        description: 'A very nice looking item with more description and even more',
        price: 50.0,
        salePrice: 30.0,
        image: Images.PH4,
        isSellingFast: false,
    },
    {
        id: 5,
        description: 'A very nice looking item',
        price: 100,
        salePrice: 50.0,
        image: Images.PH2,
        isSellingFast: false,
    },
    {
        id: 6,
        description: 'A very nice looking item',
        price: 25.0,
        salePrice: 10.0,
        image: Images.PH3,
        isSellingFast: false,
    },
    {
        id: 7,
        description: 'A very nice looking item',
        price: 20.0,
        salePrice: 9.99,
        image: Images.PH1,
        isSellingFast: false,
    },
    {
        id: 8,
        description: 'A very nice looking item',
        price: 50.0,
        salePrice: null,
        image: Images.PH4,
        isSellingFast: false,
    },
];
